### ISSUE TITLE
social distance scale up request

### ISSUE THREAD

**Issue by xie** [almiche/BackAtCha#11]
The diagram included in the README suggests that social distancing only requires a 3ft radius surrounding an individual. 

The Centers for Disease Control and Prevention ([CDC](https://www.cdc.gov/coronavirus/2019-ncov/prevent-getting-sick/social-distancing.html)) have provided guidance to `Stay at least 6 feet (2 meters) from other people`. 

Here is the diagram in question:
![image](https://user-images.githubusercontent.com/13720087/79262998-24591700-7e60-11ea-892d-c6cd3913c9e6.png)

**Comment by nnmkhang** [comment]
This is of top priority. Great work @hughxie

**Comment by almiche** [comment]
stylll I'll get to this ASAP

**Comment by jusleg** [comment]
![79262998-24591700-7e60-11ea-892d-c6cd3913c9e6](https://user-images.githubusercontent.com/4406751/79282765-056c7c00-7e84-11ea-9697-80b6d60e3c84.png)
best I could do with the tools I had

**Comment by almiche** [comment]
@jusleg  can you please make a PR. This is customer impacting we need to ship that rn.
