### ISSUE TITLE
What about internationalization ? 🇺🇸

### ISSUE THREAD

**Issue by almiche** [almiche/BackAtCha#7]
This Middleware is currently written in Canadian. We need to also translate it into 'Murican

cc: @clandry94

**Comment by clandry94** [comment]
![image](https://user-images.githubusercontent.com/5351125/78609853-a24e6a00-7831-11ea-9051-8e1c7454a3f8.png)

**Comment by almiche** [comment]
Closing this due to an overload of freedom cc: @jusleg

**Comment by jusleg** [comment]
@almiche, that’s not how we do it here 🇨🇦

**Comment by jusleg** [comment]
Sorry @clandry94, we'll close this due to an overload of freedom. Sorry again.
